### ISSUE TITLE
Piep 0.8 on PIP

### ISSUE THREAD

**Issue by maxhgerlach** [timbertson/piep#12]
Hi,

using `pip` I can apparently only get an outdated version of piep. This looks like a really useful tool especially on the compute cluster I use for numerical simulations. `0install` does not seem to be a good option to install piep there, it seems to try to pull a python distribution of its own.

`pip` just runs on the Python installation that is already there and which I intend to continue using. So would you consider updating the version on PyPI to 0.8?

Cheers, Max

**Comment by timbertson** [comment]
Uploaded now - apologies for the delay, and hope you enjoy `piep` :)

**Comment by maxhgerlach** [comment]
Thanks, it works fine!
